### ISSUE TITLE
Ckan 2.10.0 - Strange appearance

### ISSUE THREAD

**Issue by kikislater** [mutantsan/ckanext-admin-panel#4]
Is this a normal behaviour:

![image](https://github.com/mutantsan/ckanext-admin-panel/assets/13238064/bc56513b-e5d1-4c9d-b807-7393acfba2f6)

**Comment by smotornyuk** [comment]
Yes, it's the expected default theme.

The admin panel is only available to sysadmin and introduces an "alternative" way to manage CKAN. To make it obvious that the user is interacting with CKAN not in the standard way, we decided to make the default AdminUI theme different from the default CKAN theme.

Only sysadmin can see this panel and all admin pages. Sysadmin is already some kind of internal user, so showing him an unusual design is not a problem. In this way sysadmin always understands, whether he is currently working with native CKAN functionality, or with the internal CKAN part exposed by the admin panel.

Right now there are no plans to implement a UI theme that resembles the default CKAN theme. It may be done in the future when CKAN gets a bit more modern appearance, but doing it now is just wasting of effort. If you need different styles, the simplest option would be to define your own [theming extension](https://docs.ckan.org/en/2.10/theming/index.html) that overrides the admin panel's styles.

**Comment by mutantsan** [comment]
Sorry to hear that someone sees our UI implementation as a bug 🥲 I think, that the layout isn’t broken and simple, it also supports light/dark mode and we’re not planning to implement other themes for now. If you’re interested in it, you can create a PR

**Comment by kikislater** [comment]
:/ not really appealing !
This is pretty confusing to have 2 same menus, looks like a bug as you said
